apiVersion: v1
kind: Service
metadata:
  labels:
    app: kibana
    heritage: Tiller
    release: kibana
  name: kibana
  namespace: kube-system
spec:
  ports:
  - name: http
    port: 5601
    protocol: TCP
    targetPort: 5601
  selector:
    app: kibana
    release: kibana
  sessionAffinity: None
